#!/usr/bin/env python3
# Breaks folders into NYSHN ingestible chunks
# Argument 1 = target folder
# Argument 2 = file threshold

import os
import sys
import shutil

def clean(Folder):
    junk = ('._', '.DS_', 'Thumbs.db')

    for root, dirs, files in os.walk(Folder):
        for name in files:
            for search in junk:
                if search in name:
                    if os.path.exists(os.path.join(root,name)): os.remove(os.path.join(root,name))

def count(Title,Folder):
    FileCount = 0
    for root, dirs, files in os.walk(os.path.join(TargetDir,Title,Folder)):
        for name in files:
            FileCount = FileCount + 1
    return FileCount

def copyit(ChunkCount,Title,Folder):
    Chunk = "chunk-" + str(ChunkCount)
    shutil.copytree(os.path.join(TargetDir,Title,Folder),os.path.join(OutputDir,Chunk,Title,Folder))

def countbyfolder(root_dir):
    root_count = 0

    for folder in os.listdir(root_dir):
        file_count = 0
        for root, dirs, files in os.walk(os.path.join(root_dir,folder)):
            for name in files:
                file_count = file_count+1
        print(str(folder) + " : " + str(file_count))
        root_count = root_count + file_count
    print(str(root_count) + " total files.")

if __name__ == "__main__":
    #startup
    if len(sys.argv)==1:
        print("No directory specified!")
        print("chunking [directory]")
        quit()

    TargetDir = sys.argv[1]
    OutputDir = TargetDir + "_output"
    ChunkCount = 1
    CurrentChunkCount = 0

    if len(sys.argv)==3:
        Threshold = sys.argv[2]
    else:
        Threshold = 25000

    if not os.path.isdir(TargetDir):
        print("Target folder not found!")
        quit()
    if not os.path.isdir(OutputDir):
        os.mkdir(OutputDir)

    #main program loop
    print("Cleaning junk files from target folder...")
    clean(TargetDir)

    for Title in sorted(os.listdir(TargetDir)):
        for Folder in sorted(os.listdir(os.path.join(TargetDir,Title))):
            FileCount = count(Title,Folder)
            CurrentChunkCount = CurrentChunkCount + FileCount
            if int(CurrentChunkCount) > int(Threshold):
                ChunkCount = ChunkCount + 1
                CurrentChunkCount = FileCount
                copyit(ChunkCount,Title,Folder)
            else:
                copyit(ChunkCount,Title,Folder)
            print(Title + " " + Folder + " " + str(FileCount) + " files :: chunk " + str(ChunkCount) + " " + str(CurrentChunkCount) + " files")
    countbyfolder(OutputDir)
