#!/usr/bin/env python3
import os
import sys

if len(sys.argv)==1:
    print("No directory specified!")
    quit()

root_dir = sys.argv[1]
junk = ('._', '.DS_', 'Thumbs.db')
junk_count = 0

for root, dirs, files in os.walk(root_dir):
    for name in files:
        for search in junk:
            if search in name:
                junk_count = junk_count+1
                if os.path.exists(os.path.join(root,name)): os.remove(os.path.join(root,name))

print(f"\nRemoved {junk_count} junk files from {root_dir}.")
