#!/bin/bash
#Script to take unzipped India batches and convert into process.py friendly input.
#Designed to run on Mac with 'tree' installed.

STARTDIR=$1
TARGET=$STARTDIR"_unpacked"
LOAD=$2
if [[ $LOAD == "" ]]; then LOAD="100%"; fi
LOG=$STARTDIR"_log.txt"
clear

doreel() {
  #Establish what this work will work with.
  STARTDIR=${1%%/*} #Source directory
  TARGET=$STARTDIR"_unpacked" #root dir of unpacked copy.
  REEL=${1##*/} #Box name
  TITLE=${REEL%%-*} #Title as indicated by box name
  if [ ! -d "$TARGET/$TITLE" ]; then mkdir "$TARGET/$TITLE"; fi
  unset $ISSUELIST
  ISSUELIST=(`find "$1" -depth -maxdepth 1 -mindepth 1 -type d`)
      for ISSUE in "${ISSUELIST[@]}" # for each issue
        do
          ISSUENUMBER=${ISSUE##*/}
          if [ ! -e "$TARGET/$TITLE/$ISSUENUMBER" ]
            then
              cp -R $ISSUE "$TARGET/$TITLE/$ISSUENUMBER"
              if [ "$?" -ne "0" ]; then echo "Copy failed: "$ISSUE >> $LOG; fi
            else
              echo Issue already exists...
              if [ ! -e "$TARGET/$TITLE/duplicates" ]; then mkdir "$TARGET/$TITLE/duplicates"; fi
              cp -R $ISSUE "$TARGET/$TITLE/duplicates/$ISSUENUMBER"
              if [ "$?" -ne "0" ]; then echo "Copy failed: "$ISSUE >> $LOG; fi
          fi
      done #Issues
}
export -f doreel

#Setup Environment
if [ ! -e "$TARGET" ]; then mkdir "$TARGET"; fi

#Check to make sure this is what we want to work on
IFS=$'\n'
REELLIST=(`find "$STARTDIR" -depth -maxdepth 1 -mindepth 1 -type d | sort`)
for REEL in "${REELLIST[@]}"
  do
    echo -n ${REEL##*/}" "
done
echo ""
echo "Are these the reels/boxes?"
read -rsn1 INPUT
if [ "$INPUT" != "y" ]; then echo "Quitting!"; exit 1; fi
echo "Great! Getting started..."

find "$STARTDIR" -depth -maxdepth 1  -mindepth 1 -type d | parallel --jobs $LOAD doreel

#Report out to make sure everything unpacked correctly.
echo ""
echo "Done! Producing file totals."
echo -n "Origin: "
find "$1" -iname "*.pdf" | wc -l
echo -n "Unpacked: "
find "$TARGET" -iname "*.pdf" | wc -l

exit 0
