#!/usr/bin/env python3
import os
import sys
import shutil

def pdfcount(target):
    file_count = 0
    for root, dirs, files in os.walk(target):
        for name in files:
            if name.endswith('pdf'):
                file_count = file_count + 1
    return file_count

def clean(root_dir):
    junk = ('._', '.DS_Store', 'Thumbs.db')
    junk_count = 0

    for root, dirs, files in os.walk(root_dir):
        for name in files:
            for search in junk:
                if search in name:
                    junk_count = junk_count+1
                    if os.path.exists(os.path.join(root,name)): os.remove(os.path.join(root,name))

    print('Removed ' + str(junk_count) + ' junk files.')

if __name__ == "__main__":
    original_dir = sys.argv[1]
    working_dir = original_dir + "_unpacked"
    duplicate_dir = original_dir + "_duplicates"
    if not os.path.isdir(original_dir):
        print("Target folder not found!")
        quit()
    clean(original_dir)
    if not os.path.isdir(working_dir):
        os.mkdir(working_dir)
    for folder in os.listdir(original_dir):
        if os.path.isdir(os.path.join(original_dir,folder)):
            dash = folder.find('-')
            slug = folder[0:dash]
            if not os.path.isdir(os.path.join(working_dir,slug)):
                os.mkdir(os.path.join(working_dir,slug))
            for datefolder in os.listdir(os.path.join(original_dir,folder)):
                if os.path.isdir(os.path.join(original_dir,folder,datefolder)):
                    if os.path.isdir(os.path.join(working_dir,slug,datefolder)):
                        print("Duplicate folder found. " + os.path.join(working_dir,slug,datefolder))
                        if not os.path.isdir(duplicate_dir):
                            os.mkdir(duplicate_dir)
                        shutil.copytree(os.path.join(original_dir,folder,datefolder), os.path.join(duplicate_dir,folder,datefolder))
                    else:
                        print("Copying: " + os.path.join(original_dir,folder,datefolder))
                        shutil.copytree(os.path.join(original_dir,folder,datefolder), os.path.join(working_dir,slug,datefolder))
    origin_count = pdfcount(original_dir)
    unpack_count = pdfcount(working_dir)
    dup_count = 0
    print("Original PDF count: " + str(origin_count))
    print("Unpacked PDF count: " + str(unpack_count))
    if os.path.isdir(duplicate_dir):
        dup_count = pdfcount(duplicate_dir)
        print("Duplicate PDF count: " + str(dup_count))
    if origin_count == (unpack_count + dup_count):
        print("Success! File count correct!")
    else:
        print("Fail! File count incorrect!")
