#!/usr/bin/env python3
import os
import sys
import shutil
import multiprocessing as mp

def copy_file(target_file):
    root = target_file[0] #/Users/chuck/Desktop/test_shipment/box_03/frames
    file = target_file[1] #file_04.tif
    source_dir = target_file[2] #/Users/chuck/Desktop/
    dest_dir = target_file[3] #/Users/chuck/Desktop/ToProduction
    india_shipment = target_file[4] #test_india

    destination = root.replace('/frames', '') #/Users/chuck/Desktop/test_shipment/box_03
    destination = destination.replace(source_dir, '') #test_shipment/box_03
    destination_path = os.path.join(dest_dir, india_shipment, destination) #/Users/chuck/Desktop/ToProduction/test_india/test_shipment/box_03

    OriginalPath = os.path.join(root,file) #/Users/chuck/Desktop/test_shipment/box_03/frames/file_04.tif
    CopyPath = os.path.join(destination_path,file)

    if not os.path.isfile(CopyPath):
        if not os.path.isdir(destination_path):
            try:
                os.makedirs(destination_path)
            except:
                print("Directory already exists!")
        print(f"Copying {OriginalPath} to {CopyPath}")
        shutil.copy2(OriginalPath, CopyPath)
    else:
        print(f"{CopyPath} already copied. Skipping!")

def fast_scandir(dirname):
    subfolders = [f.path for f in os.scandir(dirname) if f.is_dir()]
    for dirname in list(subfolders):
        subfolders.extend(fast_scandir(dirname))
    return subfolders

if __name__ == "__main__":
    original_dir = sys.argv[1]
    india_shipment = sys.argv[2]
    source_dir = '/run/user/1000/gvfs/smb-share:server=192.168.5.110,share=datadrive/_staging'
    #source_dir = '/Users/chuck/Desktop/'
    dest_dir = '/home/rose/Staging/ToProduction'
    #dest_dir = '/Users/chuck/Desktop/ToProduction'

    if not os.path.isdir(os.path.join(source_dir,original_dir)):
        print("Target folder not found!")
        quit()

    print("Identifying frames folders...")
    subfolders = fast_scandir(os.path.join(source_dir,original_dir))
    print("Collecting tifs needing copying...")
    file_list = []
    for folder in subfolders:
        if folder.endswith('frames'):
            for root, dirs, files in os.walk(folder):
                for file in files:
                    if file.endswith('tif'):
                        file_list.append((root, file, source_dir, dest_dir, india_shipment))

    print("Copying files...")
    pool = mp.Pool(mp.cpu_count() - 1)
    task = pool.map(copy_file, file_list)
